Qt 6.2.0 Beta3 cannot proceed till qt fixes bug QTBUG-96069 Application Stops because of
W System.err: java.lang.NoSuchMethodError: no non-static method "Lorg/qtproject/qt/android/multimedia/QtAndroidMediaPlayer;.<init>()V"

And

E AndroidRuntime: FATAL EXCEPTION: qtMainLoopThread
E AndroidRuntime: Process: org.qtproject.example.camera, PID: 30583
E AndroidRuntime: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/org.qtproject.example.camera-1/lib/arm/libQt6Multimedia_armeabi-v7a.so"